# @format

apiVersion: v1
kind: Service
metadata:
  name: spring-devops-service
  labels:
    app: spring-devops-service
spec:
  type: NodePort
  selector:
    app: spring-devops-pod
  ports:
    - port: 9095
      targetPort: 9095
      nodePort: 30001
